name: mugam_flutter
description: "Mugam - Music streaming app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: any
  firebase_auth: any
  cloud_firestore: any
  firebase_storage: any
  firebase_messaging: any
  cloud_functions: any
  go_router: any
  flutter_riverpod: any
  riverpod: any
  cached_network_image: any
  image_picker: any
  camera: ^0.12.0+1
  video_player: ^2.11.1
  video_thumbnail: ^0.5.6
  flutter_video_info: ^1.3.3
  exif: ^3.3.0
  image: ^4.9.1
  native_device_orientation: ^2.1.1
  just_audio: any
  audio_session: any
  record: any
  google_fonts: any
  shared_preferences: any
  path_provider: any
  intl: any
  emoji_picker_flutter: any
  super_clipboard: any
  flutter_cache_manager: any
  share_plus: any
  device_info_plus: any
  connectivity_plus: ^7.2.0
  workmanager: ^0.9.0+3
  flutter_image_compress: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/record_start.wav
    - assets/sounds/record_stop.wav
